---
## Need to append https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt
- name: "Initial set of certificate validation"
  set_fact:
    lets_encrypt_certificate_invalidated: false

- name: "Create a build directory for fullchain assembly"
  tempfile:
    state: "directory"
    suffix: "pki"
  register: "lets_encrypt_certificate_build_dir"

- name: "Create the base PKI directories"
  file:
    path: "{{ item.path }}"
    owner: "root"
    group: "root"
    mode: "{{ item.permissions }}"
    state: "directory"
  with_items:
    - path: "/etc/ssl/private"
      permissions: "u=rwx,g=,o="
    - path: "/etc/ssl/certs"
      permissions: "u=rwx,g=rx,o=rx"
    - path: "/etc/ssl/requests"
      permissions: "u=rwx,g=o,o="

- name: "Create the Lets Encrypt signing key"
  openssl_privatekey:
    path: "/etc/ssl/private/lets_encrypt.key"

- name: "Create the resource wide key"
  openssl_privatekey:
    path: "/etc/ssl/private/{{ lets_encrypt_resource_name }}.key"

- name: "Create the certificate signing request"
  openssl_csr:
    path: "/etc/ssl/requests/{{ lets_encrypt_resource_name }}.csr"
    privatekey_path: "/etc/ssl/private/{{ lets_encrypt_resource_name }}.key"
    state: "present"
    common_name: "{{ lets_encrypt_common_name }}"
    country_name: "{{ lets_encrypt_csr_country_name }}"
    locality_name: "{{ lets_encrypt_csr_locality_name }}"
    organization_name: "{{ lets_encrypt_csr_organization_name }}"
    organizational_unit_name: "{{ lets_encrypt_csr_organizational_unit_name }}"
    email_address: "{{ lets_encrypt_csr_email_address }}"
    subject_alt_name: "{{ lets_encrypt_subject_alt_names }}"

- name: "Make the request of the Lets Encrypt API"
  letsencrypt:
    remaining_days: "{{ lets_encrypt_renew_limit }}"
    acme_directory: "{{ lets_encrypt_directory }}"
    account_email: "{{ lets_encrypt_account_email }}"
    account_key: "/etc/ssl/private/lets_encrypt.key"
    challenge: "{{ lets_encrypt_challenge_type }}"
    agreement: "{{ lets_encrypt_agreement }}"
    csr: "/etc/ssl/requests/{{ lets_encrypt_resource_name }}.csr"
    dest: "{{ lets_encrypt_certificate_build_dir.path }}/01-{{ lets_encrypt_resource_name }}.crt"
  register: acme_data

- name: "Set whether needs update"
  set_fact:
    lets_encrypt_certificate_invalidated: true
  when: acme_data.challenge_data is not undefined

- include_tasks: "configure.yml"
  with_items: "{{ lets_encrypt_resources }}"
  vars:
    lets_encrypt_resource_state: "present"
  loop_control:
    loop_var: "resource"
  when: lets_encrypt_certificate_invalidated == true

# Wait for servers to boot, DNS records to propagate, file systems to sync.
- name: "Await propagation of validation"
  pause:
    seconds: 30
  when:
    - lets_encrypt_certificate_invalidated == true
    # Wait only if it's the DNS provider
    - lets_encrypt_challenge_type == "dns-01"

- name: "Ask Lets Encrypt to validate and issue a new key"
  letsencrypt:
    acme_directory: "{{ lets_encrypt_directory }}"
    account_key: "/etc/ssl/private/lets_encrypt.key"
    challenge: "{{ lets_encrypt_challenge_type }}"
    agreement: "{{ lets_encrypt_agreement }}"
    csr: "/etc/ssl/requests/{{ lets_encrypt_resource_name }}.csr"
    dest: "{{ lets_encrypt_certificate_build_dir.path }}/01-{{ lets_encrypt_resource_name }}.crt"
    data: "{{ acme_data }}"
  when: lets_encrypt_certificate_invalidated == true

# Clean up the Route53 records
- include_tasks: "configure.yml"
  with_items: "{{ lets_encrypt_resources }}"
  vars:
    lets_encrypt_resource_state: "absent"
  loop_control:
    loop_var: "resource"
  when: lets_encrypt_certificate_invalidated == true

- name: "Copy the issued certificate to the ssl cert directory for reference"
  copy:
    src: "{{ lets_encrypt_certificate_build_dir.path }}/01-{{ lets_encrypt_resource_name }}.crt"
    dest: "/etc/ssl/certs/{{ lets_encrypt_resource_name }}.crt"
    remote_src: "yes"
  when: lets_encrypt_certificate_invalidated == true

- name: "Fetch the CA certificate"
  get_url:
    url: "https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt"
    dest: "{{ lets_encrypt_certificate_build_dir.path }}/02-chain.crt"
  when: lets_encrypt_certificate_invalidated == true

- name: "Assemble the full chain certificate"
  assemble:
    src: "{{ lets_encrypt_certificate_build_dir.path }}"
    dest: "/etc/ssl/certs/{{ lets_encrypt_resource_name }}.fullchain.crt"
    owner: "root"
    mode: "u=r,g=r,o=r"
  when: lets_encrypt_certificate_invalidated == true

- name: "Cleanup build dir"
  file:
    state: "absent"
    path: "{{ lets_encrypt_certificate_build_dir.path }}/"
